### ISSUE TITLE
Mass FIle Downloader doesn't parse file type from url

### ISSUE THREAD

**Issue by kalix123** [kalix123/Useful-Python-Tools#1]

**Comment by ihsin** [comment]
Hi @kalix123 , I would like to work on this issue. Can you please brief me its details.

**Comment by kalix123** [comment]
> 
> 
> Hi @kalix123 , I would like to work on this issue. Can you please brief me its details.

Sure thing. The program will only work for mp3 files right now. But if you provided a list of links that went to say m4a files it would still download the data to an mp3 file format. So what you need to do is get the format from the end of the url and add it on to the end of the local_filename variable (replacing .mp3)

**Comment by kalix123** [comment]
Great!
